baseurl: '/annual'
exclude: ['node_modules']

defaults:
  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "opener"
    values:
      layout: "opener"

# Build our collections
collections:
  categories:
    output: true
    permalink: /categories/:path/
  stories:
    output: true
    permalink: /stories/:path/
  opener:
    output: true
    permalink: /opener/:path/