baseurl: ""
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['node_modules', 'getData.js', 'Gemfile', 'Gemfile.lock', 'vendor', 'bin', 'Procfile', 'Rakefile']

defaults:
  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "opener"
    values:
      layout: "opener"

# Build our collections
collections:
  categories:
    output: true
    permalink: /categories/:path/
  stories:
    output: true
    permalink: /stories/:path/
  opener:
    output: true
    permalink: /opener/:path/